config/routes.rb
Petapp::Application.routes.draw do

  resources :clients

  root :to => 'static_pages#home'

  match "/about", to: "static_pages#about"
  match "/contact", to: "static_pages#contact"

end

app/models/address.rb
class Address < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :client
end

app/models/client.rb
class Client < ActiveRecord::Base
  # attr_accessible :title, :body
   attr_accessible :first_name, :last_name, :home_phone, :work_phone, :rate, :notes, :pets_attributes

  has_many :pets
  has_many :addresses

  accepts_nested_attributes_for :pets
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :name
  
  belongs_to :client
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  	@clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
    
  end

  def new
    @client = Client.new
    
  end

  def create
    
    respond_to do :json
      respond_with Client.create(params[:client])
    end
    
=begin
@client = Client.new(params[:client])
    if @client.save
      redirect_to @client
    else
      render 'new'
    end
=end
  end

  def edit
    @client = Client.find(params[:id])

  end

  def update
    @client = Client.find(params[:id])

    @client.update_attributes(params[:client])

    if @client.save
      redirect_to @client
    else
      render 'edit'
    end
  end

  def delete
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clients/delete.html.erb
<h1>Clients#delete</h1>
<p>Find me in app/views/clients/delete.html.erb</p>

app/views/clients/edit.html.erb
<h1>Edit Your Details</h1>

<div class = "row">
  <div class = "span4 offset4">

  <%= form_for @client do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :home_phone %>
    <%= f.text_field :home_phone %>

    <%= f.label :work_phone %>
    <%= f.text_field :work_phone %>

    <%= f.label :rate %>
    <%= f.text_field :rate %>

    <%= f.label :notes %>
    <%= f.text_area :notes, rows:'5' %>

    <%= f.submit "Update Client", class:"btn-large btn-primary" %>
  <% end %>
  
  </div>
</div>
<p>Find me in app/views/clients/edit.html.erb</p>

app/views/clients/index.html.erb
<h1>All Clients</h1>

<% @clients.each do |client| %>
  <p><%= link_to "#{client.first_name} #{client.last_name} - #{client.rate}", client_path(client) %> | <%= link_to "Edit", edit_client_path(client) %>
  </p>
<% end %>

<p>Find me in app/views/clients/index.html.erb</p>

app/views/clients/new.html.erb
<h1>New Client</h1>

<div class = "row" ng-controller="SignUpCtrl">
  <div class = "span6 offset3">

    <form novalidate>
      First Name: <input type="text" ng-model="client.first_name" />
      Last Name: <input type="text" ng-model="client.last_name" />

      <hr>
      <div ng-repeat="pet in pets">
        Pet Name: <input type="text" ng-model="pet.name" />
      </div>

      <button type="button" ng-click="addPetRow()">Add Pet</button>
      <br>
      <hr>
      <button type="button" ng-click="submit()" class="btn-large btn-primary">Save Client</button>
    </form>

  </div>
</div>


<p>Find me in app/views/clients/new.html.erb</p>

app/views/clients/show.html.erb
<h1>Client Details</h1>

Name: <%= @client.first_name %>
<%= @client.last_name %> | <%= link_to "Edit", edit_client_path %>

<p><%= @client.home_phone %> <br>
<%= @client.work_phone %>
</p>

Rate: <p><%= @client.rate %></p>
Notes: <p><%= @client.notes %></p>


<p>Find me in app/views/clients/show.html.erb</p>

app/views/layouts/_footer.html.erb
footerrrrrr

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Pet App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "About",    about_path %></li>
          <li><%= link_to "Contact",    contact_path %></li>

     		   <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Clients <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'All Clients', clients_path %></li>
                  <li><%= link_to 'New Client', new_client_path %></li>
                </ul>
              </li>
            </ul> 
           </nav>   

        </div>
      </div>
</header>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="PetApp">
<head>
  <title>Petapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>	

<%= yield %>

<%= debug(params) if Rails.env.development? %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>